name: Individual-CSHeld-Delay
main: com.ericlam.mc.main.InvCSHDelay
version: 1.0
authors: [Eric Lam, Hydranapse_]
depend: [CrackShot, CrackShotPlus]
commands:
  cshreload:
    aliases: [cshdelayreload]
    description: reload command
permissions:
  csh.reload:
    description: permission to reload